version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn install -DskipTests
  pre_build:
    commands:
      - echo Cleaning the project...
      - mvn clean
  build:
    commands:
      - echo Compiling the project...
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yaml
  discard-path: yes